### ISSUE TITLE
`--features=asan` doesn't work on macOS

### ISSUE THREAD

**Issue by garymm** [bazel-contrib/toolchains_llvm#192]
Building my code with `bazel build --features=asan` fails with:
`ld: file not found: external/llvm_toolchain_llvm/lib/clang/15.0.6/lib/darwin/libclang_rt.asan_osx_dynamic.dylib`

Using LLVM 15.0.6.
The file does exist. I haven't really investigated much, just filing the issue so it's common knowledge.

**Comment by siddharthab** [comment]
We stopped making dylib files available in the toolchain during the build phase because the files will not be available when running or deploying your application. But perhaps we overdid it, and we can make the .dylib files in the `lib/clang/{llvm_version}/lib/darwin/` directory available.

To test, you can add a glob expression [here](https://github.com/grailbio/bazel-toolchain/blob/master/toolchain/BUILD.llvm_repo#L60) and see if it works for you. If it does, please send a PR.

**Comment by keith** [comment]
For iOS builds with the standard bazel toolchain we copy the dylibs into the shipping bundle in that case, but that's easier in that setup because there's a clear place to do that piece

**Comment by siddharthab** [comment]
Thanks. My original imagination here was that the osx sysroot could be a good proxy of what's available at runtime. And so if a dylib is not there, it's not available. But this looks like a special case.

**Comment by timbess** [comment]
FWIW, I tested the suggested change and it works, but I ended up having to add `@llvm_toolchain//:linker-files-aarch64-darwin` as a `data` dependency of my binary so that it could find other dylibs at runtime. 
<img width="1444" alt="image" src="https://github.com/grailbio/bazel-toolchain/assets/3655689/e413debb-7c5c-40ab-a18e-94b78573d1a9">

It seems like the binary is executing in the `bazel-bin` and the dylibs aren't created in any of the places the RPATH looks for it in unless I add the linker files as a data dep.

**Comment by timbess** [comment]
<img width="687" alt="image" src="https://github.com/grailbio/bazel-toolchain/assets/3655689/613e581c-81c8-46c4-bebe-07b1cc097804">
Ok so using the `_llvm` repo to grab the `:lib` target at least doesn't directly reference my toolchain triple by name, so I'll just gate this behind a select I guess for now.
