### ISSUE TITLE
Mismatched tags

### ISSUE THREAD

**Issue by bogaczl** [bazel-contrib/toolchains_llvm#253]
The tags for some versions, e.g. 0.8.2: https://github.com/bazel-contrib/toolchains_llvm/archive/refs/tags/0.8.2.tar.gz do not point to proper source. For the link above the Readme.md contains:

BAZEL_TOOLCHAIN_TAG = "0.8.1"
BAZEL_TOOLCHAIN_SHA = "751bbe30bcaa462aef792b18bbd16c401af42fc937c42ad0ae463f099dc04ea2"

Both the version, and the sha are incorrect. Similar for version 0.9.

**Comment by siddharthab** [comment]
Unfortunately, GitHub does not maintain guarantees for the shasum being constant for source archives because they are dynamically generated. The old source archives, with the exact same contents, are gone now, and it will be non-trivial to recreate and house them. The new source archives, will have a different strip prefix (which is also the reason why their shasum is changing), but will be otherwise the same. If you don't need your older commits to work as-is, you can update the shasum and strip_prefix going forward. I can commit the new values as a file in this repo for easy reference.

This project did start generating release artifacts which are static (and hence guaranteed to be the same) from release 0.10.1 onwards.

Best practice for any project that needs to be able to run past revisions of source code as-is, is to mirror/proxy all network resources themselves or through another service.

**Comment by siddharthab** [comment]
Sorry for the inconvenience. Hopefully, you will be able to move forward.

**Comment by christophermaier** [comment]
@siddharthab Do you happen to also have the before/after checksums for the 0.5.1 release (old, I know)

**Comment by siddharthab** [comment]
I do not, but there is also nothing special I do here. Since these are dynamically generated archives, I have to fetch it from GitHub again, and my connection is not that special.

```
curl -L https://github.com/bazel-contrib/toolchains_llvm/archive/refs/tags/0.5.1.tar.gz | shasum -a 256
```

**Comment by christophermaier** [comment]
@siddharthab OK, thanks for the quick reply! :bow:
